### ISSUE TITLE
TFDisposable: Finalizer nothing do - possible memory leak

### ISSUE THREAD

**Issue by alex-zu** [migueldeicaza/TensorFlowSharp#270]
From https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensorflow.cs:

> 		~TFDisposable ()
> 		{
> 			Dispose (false);
> 		}
> 
> 		public void Dispose ()
> 		{
> 			Dispose (true);
> 			GC.SuppressFinalize (this);
> 		}
> 
> 		public virtual void Dispose (bool disposing)
> 		{
> 			if (disposing) {
> 				if (handle != IntPtr.Zero)
> 					NativeDispose (handle);
> 				handle = IntPtr.Zero;
> 			}
> 		}

If Dispose () will not called, NativeDispose also will never called.

Patch: https://gist.github.com/alex-zu/ef94a19fd7282149295fdaccb2d1302b

**Comment by migueldeicaza** [comment]
The problem is that it is not safe to invoke this from a separate thread, as the finalizer would run separately.   The proper way to fix this is to "queue" the unregistration to take place on the main thread, but that assumes there is a main loop to pump that.

Perhaps what I could do is use the current SynchronizationContext and push the NativeDispose there (but the call would have to be refactored out).

**Comment by migueldeicaza** [comment]
This is problematic for console apps, as they have no synchronization context at all.

**Comment by migueldeicaza** [comment]
Fascinating, very good catch!   I have now added support for this in the framework.

That said,  there are some objects that do not support that, so I am going to add a general framework later to flush those out
