### ISSUE TITLE
Should allow for jagged arrays as inputs to TFTensor.

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/TensorFlowSharp#33]
Just had a taste of how common they are.

Currently our implicit conversion:

```
unsafe public static implicit operator TFTensor (Array array)
```

Only handles multi-dimensional arrays, does not handle arrays of arrays.

**Comment by cesarsouza** [comment]
Jagged arrays are more common than multidimensional ones mostly because they are (used to be?) quite slow in .NET. Also, [FxCop used to (maybe it still does) recommend replacing all multidimensional arrays with jagged ones](https://msdn.microsoft.com/en-us/library/ms182277.aspx?f=255&MSPPError=-2147217396).

If it would be desirable to add support for jagged arrays, I guess the safest option would be to convert them to multidimensional arrays first, then pass them to the TFTensor(Array array) constructor (otherwise, I have no idea how to handle the "gaps" between the multiple inner vectors inside the jagged array - I guess TensorFlow needs contiguous memory areas to work on).

In this case, if anybody is interested, [I had written a method to convert jagged arrays into multidimensional ones using the machinery already present in my own framework, Accord.NET](https://github.com/accord-net/framework/blob/d6f2762f0828f67f6b5c381c32c54a6944f9cef5/Unit%20Tests/Accord.Tests.Math/Matrix/Matrix.Conversion.cs#L102). It's not the fastest implementation on earth, but it works. 

If anyone would be willing to use that implementation as a base to incorporate in TensorFlowSharp, please fell free to do so.

**Comment by cesarsouza** [comment]
Ah, I've just realized that there is a similar implementation already present in [Tensor.cs#L1034](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensor.cs#L1034).

**Comment by migueldeicaza** [comment]
This contribution has been merged.
