### ISSUE TITLE
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

### ISSUE THREAD

**Issue by sdg002** [migueldeicaza/TensorFlowSharp#354]
Hi All,

`tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
`
I see this message every time I run my executable code which loads a PB model and does some inferencing. No problems so far. I am just curios if this error message has any signficance or should I ignore it.

Thanks,
Saurabh

**Comment by MovGP0** [comment]
not every CPU supports the Advanced Vector eXtensions, so it makes sense to have the bundled .dll not supporting it. Tensorflow still works by falling back to SSE. It's simply a bit slower in certain situations.

**Comment by MovGP0** [comment]
if you really need the maximum performance, you need to download the Tensorflow source, compile it yourself, and replace the .dll. 

There might be the possibility to determine if the CPU supports AVX and then bind to the appropriate Tensorflow .dll. But this might require to ship multiple versions of the Tensorflow .dll, and select the correct binding using Dependency Injection (or some hackery), which might be impractical. 

However, you might prefer to use the GPU instead of the CPU in such situations anyway.

**Comment by sdg002** [comment]
Thanks so much for the clarification. I will stick to CPU for now. Works well on Azure Web App service.

**Comment by MihaMarkic** [comment]
But the situation with GPU is similar, right? You need a different library. I wish the library would be smart enough to adapt to different hardware.
To me it sounds like shipping multiple versions and determine the best at runtime might be the best way to go.

**Comment by migueldeicaza** [comment]
I agree it would be (and I would like to solve the CPU/GPU one), but the problem is that for CPU alone there are many combinations, and I am not ready to ship a dozen versions of what is already a bloated executable.
