### ISSUE TITLE
Memory leak caused by not having a collecting stage for handles.

### ISSUE THREAD

**Issue by pwimmer** [migueldeicaza/TensorFlowSharp#365]
TFTensor leave behind a pinned object that cannot be garbage collected.

Initialize a tensor from an array and let the garbage collector collect it. Data array is still pinned afterwards.

The error is in TFDisposable.Dispose. The line

if (disposing)

should be removed.

See https://stackoverflow.com/questions/898828/finalize-dispose-pattern-in-c-sharp how to correctly implement the dispose pattern.

**Comment by migueldeicaza** [comment]
The problem is that fundamentally, this assumes that releasing objects is a thead-safe operation, and it is not clear to me that they are.

The reason for the guard on dispose is that it prevents objects from being released on the Finalizer thread, now I think that you have a solid claim that this is a problem.    Applications with a mainloop are able to come up with a proper solution by "queuing" operations on the main thread.

The issue with TensorFlowSharp is that it is rarely used in a form that uses a mainloop, so we can not rely on this.

What I think the proper fix is, is that if Dispose=false, we should queue the handle for proper disposal on the thread running the code.   Something like:

```
if (!disposing)
    handles_to_dispose.Add (handle);
```

Then provide a method that is called in assorted places:

```
void DisposePendingObjects ()
{
   if (handles_to_dispose.Count > 0){
      foreach (var h in handles_to_dispose) h.TF_Release (h);
     handles_to_dispose.Clear ();
   }
}
```

And then call this from various places.

**Comment by migueldeicaza** [comment]
Well, my bad, I forgot I had done the research on this before.

TFTensors are disposable from a background thread, so they subclass TFDisposableThreadSafe, which does not have the "if (disposing)" pattern in place.

Generally, the "Dispose" pattern with unmanaged resources guidance is only valid when the unmanaged resource can be safely disposed from a thread.   This is not always the case, I will suggest that we fix this in our documentation.

**Comment by migueldeicaza** [comment]
Ok suggested a fix for our documentation:

https://github.com/dotnet/docs/pull/9416

That said, the issue that you are experiencing must be different, perhaps not draining the finalizer queue fast enough, because the finalizer already has the call there.

So my suggestion to drain the queue as described still applies.

**Comment by migueldeicaza** [comment]
Reopening becasue this optimization is still worth doing, and would solve some surprises that happen when loading a lot of data in a tight loop and the GC has not executed.

**Comment by migueldeicaza** [comment]
Actually, without the GC running the optimization is worthless.   

I am at a loss as to how we could solve this (and there is a similar issue filed, which is why this raised on my radar)
