### ISSUE TITLE
Sort out how to do NetStandard packaging

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/TensorFlowSharp#71]
I would like to repackage the NuGet using .NET Standard.   I believe Nugettizer-3000 can help me do that, but I believe I might need to change my library target to do that.

**Comment by mwk888** [comment]
@migueldeicaza I just tried a trivial Windows console app test using nuget to add TFS and the app fails at launch (error below). Is this something that will be fixed by your planned NuGet change or should I open an issue?

`System.BadImageFormatException: 'Could not load file or assembly 'TensorFlowSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.'`

**Comment by andykernahan** [comment]
@mwk888 That exception is most likely because your platform target is not x64; libtensorflow.dll is 64bit.

**Comment by mwk888** [comment]
@andykernahan You're right, thanks! I didn't notice the new project defaulted to x32

**Comment by migueldeicaza** [comment]
It is shipping .NET Standard libraries now.
