### ISSUE TITLE
[Enhancement] Enable Unity integration by targeting .NET 3.5

### ISSUE THREAD

**Issue by mwk888** [migueldeicaza/TensorFlowSharp#74]
Background: I'm working on multi-agent simulations in 3D. Unity is a good platform because it is C#, targets Mac/Windows/Android/iOS and has strong 3D. Unfortunately Unity is limited to (roughly) .NET 3.5 vs TensorFlowSharp target 4.6.1.

This may sound crazy :) but is it feasible to change TensorFlowSharp to target .NET 3.5?

The only issue I'm aware off offhand is C# 7.0 tuples. Apparently there are solutions targeting .NET 3.5 https://stackoverflow.com/questions/7469700/is-there-something-like-tuple-in-net-3-5 but I don't know if these are any good.

I have done Unity plugins before so happy to take on that part.

**Comment by mwk888** [comment]
UPDATE I checked the latest discussion by Unity about when they expect to support .NET Standard https://feedback.unity3d.com/suggestions/dot-net-standard-compatibility

The good news is they seem more serious about it. The bad news is a realistic roadmap for mobile support is still more than a year away.

This suggestion may just depend on how important mobile is for TensorFlowSharp. Virtually all C# deployment on mobile is via Unity so .NET 3.5 support enables that (and of course 3D). If lowering the .NET version target is easy that's a win, but I can't judge the difficulty.

**Comment by migueldeicaza** [comment]
Unity should have an upgraded Mono this summer, so that should work.

TensorFlowSharp is a personal project that I use partly to learn, partly to explore API design, partly to dogfood our products.   Going back to that would undermine the purpose of the project.   That said, if you really need that capability, you can still fork the code and make a .NET 3.5 port.

**Comment by TejaswiniiB** [comment]
@migueldeicaza , @mwk888 
Hi, I too have the same requirement: TensorflowSharp support for .NET 3.5. Is it available now, or any inputs you can give for us to have such a one?

To fork the code and make a .NET 3.5 port,
is there a list things mentioning parts of TensorflowSharp project which don't work for .NET 3.5, so that we can modify that code as required?

**Comment by ryuuguu** [comment]
Unity 2018.1 beta supports .Net 4.xx also in 2017.x you in player settings you change the Scripting runtime version to 4.x, but you would still not be able to use TFSharp in the editor so it is better to go with 2018.1.beta it will be out of beta in a month or two.
